<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1585553383872' stop='1585553494539'>
    <name>Second Pull</name>
    <title>Second Pull</title>
    <test-cases>
        <test-case start='1585553383872' status='failed' stop='1585553390818'>
            <name>Add to Comparison</name>
            <title>Add to Comparison</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: element not interactable
                  (Session info: headless chrome=80.0.3987.149)
                  (Driver info: chromedriver=80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}),platform=Windows NT 10.0.17763 x86_64)</message>
                <stack-trace>ElementNotVisibleError: element not interactable
                  (Session info: headless chrome=80.0.3987.149)
                  (Driver info: chromedriver=80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}),platform=Windows NT 10.0.17763 x86_64)
                    at Object.checkLegacyResponse (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
                    at parseHttpResponse (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
                    at C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (internal/process/task_queues.js:93:5)Error
                    at ElementArrayFinder.applyAction_ (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
                    at ElementArrayFinder.&lt;computed> [as click] (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
                    at ElementFinder.&lt;computed> [as click] (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
                    at yandexMarketMethods.goToCompareAndCheck (C:\Users\Alexey\automationJS\methods\yandexMarketMethods.js:34:50)
                    at UserContext.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:18:35)
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (internal/process/task_queues.js:93:5)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:14:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585553390818' status='failed' stop='1585553494393'>
            <name>Remove from Comparison</name>
            <title>Remove from Comparison</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:59554</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:59554
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:22:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585553494393' status='failed' stop='1585553494515'>
            <name>Sort in Market</name>
            <title>Sort in Market</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:59554</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:59554
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:8:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585553494515' status='failed' stop='1585553494522'>
            <name>Sort by tag</name>
            <title>Sort by tag</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:59554</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:59554
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:8:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585553494522' status='failed' stop='1585553494529'>
            <name>Yandex Music</name>
            <title>Yandex Music</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:59554</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:59554
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:8:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585553494529' status='failed' stop='1585553494537'>
            <name>Play Music</name>
            <title>Play Music</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:59554</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:59554
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:8:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>