<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1585554205654' stop='1585554323871'>
    <name>Second Pull</name>
    <title>Second Pull</title>
    <test-cases>
        <test-case start='1585554205655' status='failed' stop='1585554221209'>
            <name>Add to Comparison</name>
            <title>Add to Comparison</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: No element found using locator: by.cssContainingText("span.header2-menu__text", "Сравнение")</message>
                <stack-trace>NoSuchElementError: No element found using locator: by.cssContainingText("span.header2-menu__text", "Сравнение")
                    at C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27
                    at processTicksAndRejections (internal/process/task_queues.js:93:5)Error
                    at ElementArrayFinder.applyAction_ (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
                    at ElementArrayFinder.&lt;computed> [as click] (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
                    at ElementFinder.&lt;computed> [as click] (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
                    at yandexMarketMethods.goToCompareAndCheck (C:\Users\Alexey\automationJS\methods\yandexMarketMethods.js:34:50)
                    at UserContext.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:18:35)
                    at processTicksAndRejections (internal/process/task_queues.js:93:5)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:14:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585554221210' status='failed' stop='1585554323834'>
            <name>Remove from Comparison</name>
            <title>Remove from Comparison</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:57164</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:57164
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:22:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585554323834' status='failed' stop='1585554323853'>
            <name>Sort in Market</name>
            <title>Sort in Market</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:57164</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:57164
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:8:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585554323853' status='failed' stop='1585554323858'>
            <name>Sort by tag</name>
            <title>Sort by tag</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:57164</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:57164
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:8:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585554323858' status='failed' stop='1585554323864'>
            <name>Yandex Music</name>
            <title>Yandex Music</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:57164</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:57164
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:8:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1585554323864' status='failed' stop='1585554323869'>
            <name>Play Music</name>
            <title>Play Music</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: EADDRINUSE connect EADDRINUSE 127.0.0.1:57164</message>
                <stack-trace>Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:57164
                    at ClientRequest.&lt;anonymous> (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
                    at ClientRequest.emit (events.js:210:5)
                    at Socket.socketErrorListener (_http_client.js:406:9)
                    at Socket.emit (events.js:210:5)
                    at emitErrorNT (internal/streams/destroy.js:91:8)
                    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
                    at processTicksAndRejections (internal/process/task_queues.js:80:21)
                From asynchronous test: 
                Error
                    at Suite.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:8:5)
                    at addSpecsToSuite (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\Alexey\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (C:\Users\Alexey\automationJS\tests\secondPull.js:1:1)
                    at Module._compile (internal/modules/cjs/loader.js:945:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
                    at Module.load (internal/modules/cjs/loader.js:798:32)
                    at Function.Module._load (internal/modules/cjs/loader.js:711:12)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>